version: '3.0'

expectations:
  population_size: 1000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort --output-format csv.gz --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  describe:
    run: r:latest -e 'rmarkdown::render("analysis/report.Rmd", output_dir="/workspace/output")'
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        html: output/report.html